name: Setup CI
on:
  workflow_dispatch:
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: upptime/uptime-monitor@v1.41.0
        with:
          token: ${{ secrets.GH_PAT }}
      - uses: upptime/graphs@v1.2.18
        with:
          token: ${{ secrets.GH_PAT }}
      - uses: upptime/uptime-monitor@v1.41.0
        with:
          token: ${{ secrets.GH_PAT }}
      - uses: upptime/uptime-monitor@v1.41.0
        with:
          token: ${{ secrets.GH_PAT }}
      - uses: upptime/status-page@v1.17.0
        with:
          token: ${{ secrets.GH_PAT }}
